{{- if not .Values.cache.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-cache
  labels:
    {{- include "fleet.labels" . | nindent 4 }}
data:
  FLEET_REDIS_ADDRESS: "{{ .Values.cache.address }}"
{{- end }}
---
{{- if not .Values.database.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-database
  labels:
    {{- include "fleet.labels" . | nindent 4 }}
data:
  FLEET_MYSQL_HOST: "{{ .Values.database.host }}"
  FLEET_MYSQL_PORT: "{{ .Values.database.port }}"
  MYSQL_DATABASE: "{{ .Values.database.database }}"
  MYSQL_USER: "{{ .Values.database.username }}"
{{- end }}
