{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: fleet-database
  labels:
    {{- include "fleet.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.passwordKey }}: {{ .Values.database.password | quote }}
{{- end }}
